# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: class-pvc
# spec: 
#   storageClassName: pj-sc
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 5Gi
