apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  requirements:
    - key: node.kubernetes.io/instance-type
      operator: In
      values: ["t3a.2xlarge", "t3a.xlarge", "t3.xlarge", "m5.large"]
    - key: kubernetes.io/arch
      operator: In
      values: ["amd64"]
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["on-demand"]
  provider:
    instanceProfile: karpenter-node-instance-profile
    subnetSelector:
      kubernetes.io/cluster/univ-eks: owned
    securityGroupSelector:
      aws:eks:cluster-name: univ-eks
  ttlSecondsAfterEmpty: 30
