---
apiVersion: v1
Kind: Service
metadata:
  name: cert-service
spec:
  selector:
    app: cert
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-deploy
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: cert
  template:
    metadata: 
      labels:
        app: cert
    spec:
      containers:
        - name: cert-ctn
          image: nginx
          ports:
          - containerPort: 80
          resources: 
            limits:
              memory: "1Gi"
              cpu: '1'
            request:
              memory: "1Gi"
              cpu: '1'
      volumes:
        - name: cert-volume
          PersistentVolumeClaim:
            claimName: cert-pvc